POST  http://localhost:5555 HTTP/1.1
content-type: application/json
CSRF-Token: akwT2xZH-IOt2o7b3wJjSS-VsGE7v4nq5d2E

{
    "email":"taro@example.com",
    "username":"taro",
    "password":"password"
}